import Image from 'next/image'
import Link from 'next/link'

export default function animations() {
  return (
    <main className="bg-[url('/bg.svg')] flex min-h-screen flex-col items-center justify-center p-10">
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jLD0uf11LnI?si=WGKeP5Uijzp0LJ8E" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/Kj7iN387XU0?si=1A_bjaJgi3ROiZy1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/bI0ci3flFXk?si=E1OA__Wi32yDP3cf" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/5rt-3kc1CGM?si=deINNc9ws0tN_uz_" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/CDKEtL9WUTc?si=7yoUWtflUkFM9mdp" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/eGcCHHosy7k?si=BlhzJ0JpmErOQVSz" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/y4KAtF5Xckw?si=iKFkmvkUTQrjN83L" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/7yHNzUOntRo?si=3Z06qU4poO5jFVs0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/zC_x_vXPmFs?si=fqgxyMBvqC2nEGXA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/IRODgsVLnBw?si=nT7T7eQw5uRkqbyN" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jHyfB8GESd8?si=lmi5fLYBuHDt-U-9" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/30fbS1x0i5M?si=bS_YDccNwJjL45cC" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/RxeYO9oe6F8?si=hTjvlM3DdhftTHFL" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jjho8dmKmbA?si=kyIL2WHEfh9boNya" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/VcCUKFG-aLE?si=-pg2lh4nd0BAiQ1X" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/hvGiSSpoc9Q?si=RkIOBklC6c_99Jc4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/46vcbYOi2r0?si=RkPeq0AmcJszoJ2q" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/j806ZJBTEA4?si=UkIExdj4YZ8kG0lW" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/3Xzb2uNlf0s?si=THd3gO4vMuTrWM0U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/z1or0DOjXj4?si=-WIFk5qvOftYx0o5" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/u9c8wOX7oXU?si=ZpYUAPX7eTWraQ2E" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jYS-1pf0GHA?si=EK0mzq86CxTYxudn" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/pqRfrPvREkk?si=B2SQ-pgWfOUHDtZ7" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/64hz3_8gbpg?si=fEa3JN4-fl9vLGW2" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/_OM2Af1lQpY?si=VFmnq4ye6hAH6N22" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/AoJ6Cg-Rjp8?si=xt5kpZdFZQ46XP0O" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <iframe className='w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/f5maPFP0IaQ?si=iEw9ShD5MKA3GNR5" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </main>
  )
}
