import Image from 'next/image'
import Link from 'next/link'

export default function animations() {
  return (
    <main className="bg-[url('/chessy.svg')] flex min-h-screen flex-col items-center justify-center p-10">
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/r0ZpfTsHS80?si=uddaEkJ8TEq5bpum"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/B68AbLuD7hA?si=Tx7rjPlGN2i33IJy"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/B6A6sxkBd9g?si=XLxQBFBPkjzxtWS9"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/5YKbI5EmND8?si=TV2ugPw5FATy6bjG"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/yoyic2P8Ijo?si=4Qbqx5uOuskWAdRY"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/t_WQ8enK7Lg?si=cTejOtf6VQgrBFGi"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jp2NhGqJzbM?si=wkYDO_NiI6SwoTVE"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
<iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/a7SkWyLhLbY?si=QTSiqoE6p7r3nao3"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/QmN8cHspYrg?si=ZYv-Q8gqj1Kfm78v"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>

      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/_S8r_vdc9mk?si=1AqQ5O9GJjqtdmFz"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/TZuyR4tltr4?si=6gSGPAjJbP73Eei8"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>

      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jLD0uf11LnI?si=WGKeP5Uijzp0LJ8E"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/Kj7iN387XU0?si=1A_bjaJgi3ROiZy1"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/yit7-dEmvQs?si=ApKnGChvBI_sgkxp"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/bI0ci3flFXk?si=E1OA__Wi32yDP3cf"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/5rt-3kc1CGM?si=deINNc9ws0tN_uz_"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/CDKEtL9WUTc?si=7yoUWtflUkFM9mdp"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/eGcCHHosy7k?si=BlhzJ0JpmErOQVSz"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/y4KAtF5Xckw?si=iKFkmvkUTQrjN83L"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/7yHNzUOntRo?si=3Z06qU4poO5jFVs0"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/zC_x_vXPmFs?si=fqgxyMBvqC2nEGXA"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/IRODgsVLnBw?si=nT7T7eQw5uRkqbyN"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jHyfB8GESd8?si=lmi5fLYBuHDt-U-9"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/30fbS1x0i5M?si=bS_YDccNwJjL45cC"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/RxeYO9oe6F8?si=hTjvlM3DdhftTHFL"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jjho8dmKmbA?si=kyIL2WHEfh9boNya"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/VcCUKFG-aLE?si=-pg2lh4nd0BAiQ1X"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/hvGiSSpoc9Q?si=RkIOBklC6c_99Jc4"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/46vcbYOi2r0?si=RkPeq0AmcJszoJ2q"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/j806ZJBTEA4?si=UkIExdj4YZ8kG0lW"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/3Xzb2uNlf0s?si=THd3gO4vMuTrWM0U"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/z1or0DOjXj4?si=-WIFk5qvOftYx0o5"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/u9c8wOX7oXU?si=ZpYUAPX7eTWraQ2E"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/jYS-1pf0GHA?si=EK0mzq86CxTYxudn"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/pqRfrPvREkk?si=B2SQ-pgWfOUHDtZ7"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/64hz3_8gbpg?si=fEa3JN4-fl9vLGW2"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/_OM2Af1lQpY?si=VFmnq4ye6hAH6N22"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/AoJ6Cg-Rjp8?si=xt5kpZdFZQ46XP0O"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
      <iframe className='w-6/6 lg:w-3/6 pb-10 rounded-xl aspect-video' src="https://www.youtube.com/embed/f5maPFP0IaQ?si=iEw9ShD5MKA3GNR5"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" loading="lazy" allowfullscreen></iframe>
    </main>
  )
}
